"""Change reaction type to integer code

Revision ID: 27a8d37d3c4e
Revises: ddfc03945ec7
Create Date: 2025-09-24 11:59:23.505020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27a8d37d3c4e'
down_revision: Union[str, None] = 'ddfc03945ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactions', sa.Column('code', sa.Integer(), nullable=False))
    op.drop_column('reactions', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactions', sa.Column('type', mysql.ENUM('like', 'love', 'haha', 'wow', 'sad', 'angry'), nullable=False))
    op.drop_column('reactions', 'code')
    # ### end Alembic commands ###
