"""Add v2 fields: deleted, created_at, updated_at

Revision ID: 76f027e5d2c8
Revises: 27a8d37d3c4e
Create Date: 2025-09-24 16:58:14.548615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f027e5d2c8'
down_revision: Union[str, None] = '27a8d37d3c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('blogs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('blogs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('reactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('reactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactions', 'updated_at')
    op.drop_column('reactions', 'created_at')
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'deleted')
    op.drop_column('blogs', 'updated_at')
    op.drop_column('blogs', 'created_at')
    op.drop_column('blogs', 'deleted')
    # ### end Alembic commands ###
