"""Add ReactionType enum to reactions table

Revision ID: ddfc03945ec7
Revises: ad955aa74c09
Create Date: 2025-09-23 14:03:42.886389

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ddfc03945ec7'
down_revision: Union[str, None] = 'ad955aa74c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the Enum type
reaction_enum = sa.Enum('like', 'love', 'haha', 'wow', 'sad', 'angry', name='reactiontype')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type in DB
    reaction_enum.create(op.get_bind(), checkfirst=True)

    # Alter the column to use the Enum type
    op.alter_column(
        'reactions', 'type',
        existing_type=mysql.VARCHAR(length=50),
        type_=reaction_enum,
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert column back to string
    op.alter_column(
        'reactions', 'type',
        existing_type=reaction_enum,
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False
    )

    # Drop the Enum type
    reaction_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

